### ISSUE TITLE
代码问题咨询

### ISSUE THREAD

**Issue by shu616048151** [ThalesGroup/pythagore-mod-reco#11]
通过拉取代码发现，你这边所提出的算法。在RML2016数据集上并没有优异的表现。但是在AugMod数据集上表现不错。
问题一：想问一下该算法只有在AugMod上才表现不错？
问题二：AugMod是本人自己制作的数据集吗？？？？有什么办法可以自己生成？？？

**Comment by helion-du-mas-des-bourboux-thales** [comment]
Hello @shu616048151, any remarks on this issue?

**Comment by shu616048151** [comment]
在公开数据集的流程图中无法训练，并且希望能够公开数据集制作代码

**Comment by helion-du-mas-des-bourboux-thales** [comment]
Any news @shu616048151

**Comment by helion-du-mas-des-bourboux-thales** [comment]
Close, for not clear what is asked.
